version: "3.7"
services:
  nginx:
    build:
      context: ./localNginx #ローカル開発用です。HTTPSポートは公開しません
      dockerfile: Dockerfile
    ports:
      - target: 80
        published: 8080
        protocol: tcp
  backend:
    init: true
    depends_on:
      - mysql
      - mysql-slave
    build:
      context: ../development/backend
      dockerfile: Dockerfile
  frontend:
    build:
      context: ./dummyFrontend #dummyFrontendはダミーのhtmlのみ返却します。
      dockerfile: Dockerfile
  mysql:
    build:
      context: ./localMysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: "app"
      MYSQL_USER: "backend"
      MYSQL_PASSWORD: "backend"
  mysql-slave:
    build:
      context: ./../development/mysql-slave
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "app"
      MYSQL_USER: "backend"
      MYSQL_PASSWORD: "backend"
      MYSQL_MASTER_HOST: "mysql"
