version: "3.7"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - target: 443
        published: 443
        protocol: tcp
      - target: 80
        published: 8080
        protocol: tcp
    volumes:
      - /da/tls:/etc/nginx/tls
  backend:
    init: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ../volume/backend/file:/backend/file
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - 3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: "app"
      MYSQL_USER: "backend"
      MYSQL_PASSWORD: "backend"
    volumes:
      - ../volume/mysql:/var/lib/mysql
  mysql-slave:
    image: mysql:8.0
    ports:
      - 3306
    depends_on:
      - mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: "app"
      MYSQL_USER: "backend"
      MYSQL_PASSWORD: "backend"
      MYSQL_MASTER_HOST: "mysql"
    volumes:
      - ./mysql/slave.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/start-slave.sh:/docker-entrypoint-initdb.d/start-slave.sh
